---
development:
  cloud_name: <%= Rails.application.credentials[Rails.env.to_sym][:cloud_name] %>
  api_key: <%= Rails.application.credentials[Rails.env.to_sym][:api_key] %>
  api_secret: <%= Rails.application.credentials[Rails.env.to_sym][:api_secret] %>
  enhance_image_tag: <%= Rails.application.credentials[Rails.env.to_sym][:enhance_image_tag] %>
  static_file_support: <%= Rails.application.credentials[Rails.env.to_sym][:static_file_support] %>
production:
  cloud_name: <%= Rails.application.credentials[Rails.env.to_sym][:cloud_name] %>
  api_key: <%= Rails.application.credentials[Rails.env.to_sym][:api_key] %>
  api_secret: <%= Rails.application.credentials[Rails.env.to_sym][:api_secret] %>
  enhance_image_tag: <%= Rails.application.credentials[Rails.env.to_sym][:enhance_image_tag] %>
  static_file_support: <%= Rails.application.credentials[Rails.env.to_sym][:static_file_support] %>
test:
  cloud_name: <%= Rails.application.credentials[Rails.env.to_sym][:cloud_name] %>
  api_key: <%= Rails.application.credentials[Rails.env.to_sym][:api_key] %>
  api_secret: <%= Rails.application.credentials[Rails.env.to_sym][:api_secret] %>
  enhance_image_tag: <%= Rails.application.credentials[Rails.env.to_sym][:enhance_image_tag] %>
  static_file_support: <%= Rails.application.credentials[Rails.env.to_sym][:static_file_support] %>
