---
development:
  cloud_name: dcytgrhgd
  api_key: '379811168911235'
  api_secret: RNoETEBT1CqeO7vbkjIEEw04xmo
  enhance_image_tag: true
  static_file_support: false
production:
  cloud_name: dcytgrhgd
  api_key: '379811168911235'
  api_secret: RNoETEBT1CqeO7vbkjIEEw04xmo
  enhance_image_tag: true
  static_file_support: true
test:
  cloud_name: dcytgrhgd
  api_key: '379811168911235'
  api_secret: RNoETEBT1CqeO7vbkjIEEw04xmo
  enhance_image_tag: true
  static_file_support: false
